
package br.personal.soa.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.1
 * Mon Mar 28 15:44:28 BRT 2022
 * Generated source version: 3.5.1
 */

@XmlRootElement(name = "subtrair", namespace = "http://soa.personal.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subtrair", namespace = "http://soa.personal.br/", propOrder = {"arg0", "arg1"})

public class Subtrair {

    @XmlElement(name = "arg0")
    private double arg0;
    @XmlElement(name = "arg1")
    private double arg1;

    public double getArg0() {
        return this.arg0;
    }

    public void setArg0(double newArg0)  {
        this.arg0 = newArg0;
    }

    public double getArg1() {
        return this.arg1;
    }

    public void setArg1(double newArg1)  {
        this.arg1 = newArg1;
    }

}

