
package br.personal.soa.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.1
 * Mon Mar 28 15:44:28 BRT 2022
 * Generated source version: 3.5.1
 */

@XmlRootElement(name = "tg", namespace = "http://soa.personal.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tg", namespace = "http://soa.personal.br/")

public class Tg {

    @XmlElement(name = "arg0")
    private double arg0;

    public double getArg0() {
        return this.arg0;
    }

    public void setArg0(double newArg0)  {
        this.arg0 = newArg0;
    }

}

