
package br.personal.soa;

import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-28T15:44:29.282-03:00
 * Generated source version: 3.5.1
 *
 */

@WebService
public interface Calculadora_PortType {

    public double sen(

        double arg0
    );

    public double subtrair(

        double arg0,
        double arg1
    );

    public double multiplicar(

        double arg0,
        double arg1
    );

    public double dividir(

        double arg0,
        double arg1
    );

    public double pow(

        double arg0,
        double arg1
    );

    public double somar(

        double arg0,
        double arg1
    );

    public double sqrt(

        double arg0
    );

    public double cos(

        double arg0
    );

    public double tg(

        double arg0
    );
}
