
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package br.personal.soa;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-28T15:44:29.307-03:00
 * Generated source version: 3.5.1
 *
 */
public class Calculadora_PortTypeClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://soa.personal.br/", "CalculadoraService");
        QName portName = new QName("http://soa.personal.br/", "CalculadoraPort");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                        "http://localhost:9090/CalculadoraPort");
        br.personal.soa.Calculadora_PortType client = service.getPort(portName,  br.personal.soa.Calculadora_PortType.class);

        
        System.out.println("Testando métodos básicos da calculadora");
        System.out.println("3 + 5 = "  + client.somar(3, 5));
        System.out.println("3 - 5 = "  + client.subtrair(3, 5));
        System.out.println("3 * 5 = "  + client.multiplicar(3, 5));
        System.out.println("3 / 5 = "  + client.dividir(3, 5));
        System.out.println("Testando métodos extras da calculadora");
        System.out.println("sen(0)= "  + client.sen(0));
        System.out.println("cos(0)= "  + client.cos(0));
        System.out.println("tg(0)= "   + client.tg(0));
        System.out.println("3² = "     + client.pow(3, 2));
        System.out.println("sqrt(2)= " + client.sqrt(2));
    }

}