
package br.personal.soa;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-28T15:44:29.306-03:00
 * Generated source version: 3.5.1
 *
 */

public class Calculadora_PortTypeServer{

    protected Calculadora_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new br.personal.soa.Calculadora();
        String address = "http://localhost:9090/CalculadoraPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new Calculadora_PortTypeServer();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}

